require:
  - rubocop-factory_bot
  - rubocop-rspec_rails

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/archive/*'
    - 'config/initializers/secret_token.rb'
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Metrics/BlockLength:
  Exclude:
    - '**/Guardfile'
    - '**/*.rake'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'spec/**/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HttpPositionalArguments:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SubjectStub:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/VariableName:
  EnforcedStyle: snake_case

FactoryBot:
  Include:
    - "**/spec/factories/**/*.rb"
    - "**/db/seeds/*.rb"

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/v1/**/*'
    - 'app/resources/v1/**/*'
    - 'app/processors/v1/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

# Enable cops that are disabled by default, but are useful nonetheless
# See https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml

Rails:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/OptionHash:
  Enabled: true
  Exclude:
    - 'app/resources/v1/**/*'
    - 'app/paginators/*'

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: false
