version: '3'
services:
  db:
    env_file: .env
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    env_file: .env
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/var/lib/redis/data
  web:
    env_file: .env
    environment:
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: