version: '3'

services:
  db:
    image: postgres:14.2
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUNDLE_INSTALL_EXCLUDE=''
    depends_on:
      - db
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app

volumes:
  postgres_data:
