version: '2'

services:
  db:
    env_file: .env
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    env_file: .env
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/var/lib/redis/data
  sidekiq:
    env_file: .env
    image: docker.csvalpha.nl/amber-api:latest
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
  web:
    env_file: .env
    image: docker.csvalpha.nl/amber-api:latest
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./log:/app/log
    labels:
    - traefik.enable=true
    - traefik.port=3000
    - traefik.api.frontend.rule=Host:$HOST;PathPrefixStrip:/api
    - traefik.static.frontend.rule=Host:$HOST;PathPrefix:/uploads,/ical,/sidekiq

volumes:
  postgres_data:
  redis_data:
