version: '2'

services:
  db:
    env_file: .env
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    env_file: .env
    image: 'redis:6.2-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/var/lib/redis/data
  sidekiq:
    env_file: .env
    image: ghcr.io/csvalpha/amber-api:latest
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
  web:
    env_file: .env
    image: ghcr.io/csvalpha/amber-api:latest
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./log:/app/log
    labels:
      - traefik.enable=true
      - traefik.http.routers.amber-api-staging.rule=Host(`$HOST`) && PathPrefix(`/api`, `/uploads`, `/sidekiq`, `/webdav`, `/ical`)
      - traefik.http.routers.amber-api-staging.middlewares=amber-api-strip@file
      - traefik.http.routers.amber-api-staging.tls.certresolver=default


volumes:
  postgres_data:
  redis_data:
